type: object
properties:
  description:
    type: string
    description: The description of the product
    minLength: 3
    maxLength: 255
  dimensions:
    $ref: dimensions.yaml
  categories:
    type: array
    description: The category codes for the product
    items:
      type: string
  images:
    type: array
    items:
      $ref: image.yaml
  price:
    type: string
    pattern: ^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$
  cost:
    type: string
    pattern: ^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$
required:
  - description
  - price