get:
  tags:
    - Products
  summary: Get a list of products
  description: Get a list of products.
  operationId: listProducts
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product_list.yaml
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/Problem.yaml
post: 
  tags: 
    -  Product
  summary: Create new product
  description: Create a new product.
  operationId: createProduct
  requestBody: 
    content: 
      application/json:
        schema: 
          $ref: ../../components/schemas/v1/product.yaml
  responses: 
    '201':
      description: Created
      headers: 
        Location:
          description: Location of the new resource
          schema: 
            type: string
            example: /v1/products/bec5e7a0-bd40-4380-b787-f1388d171509
    '400':
      description: Bad Request
      content: 
        application/json:
          schema: 
            $ref: ../../components/schemas/Problem.yaml
    
